import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import IconLogin from '../icon/icon-login.svg';

export default function Login() {
  return (
    <>
      <Head>
        <title>APP-BC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="flex flex-row min-h-screen">
        <div className="bg-[#8ECAE6] w-[35%] flex items-center justify-center rounded-r-lg">
            <div className="flex flex-col items-center justify-center">
                <Image src={IconLogin}/>
            </div>
        </div>
        <div>
            <div className="formulario-login">lalala</div>
        </div>
        {/* <form action="/admin" method="POST">
        
          <div className="d-flex justify-content-center p-2">
            <div className="col-md-4">
              <div>
                <h2>Login</h2>
              </div>
              <div className="form-group">
                <label className="form-label" htmlFor="username">Usuário</label>
                <input type="text" id="username" name="username" className="form-control" />
              </div>
              <div className="form-group">
                <label className="form-label" htmlFor="password">Senha</label>  
                <input type="password" id="password" name="password" className="form-control" />
              </div>
              <div className="form-group p-2">
                <button className="btn btn-outline-success" type="submit">Login</button>
                <Link className="btn btn-outline-info" href="/">Voltar</Link>
              </div>
            </div>
          </div>
        </form> */}
      </div>  
    </>
  );
}